export interface NeetCodeSeed {
  question_number: number;
  title: string;
  category: string;
  difficulty: "easy" | "medium" | "hard";
  neetcode_url: string;
  leetcode_url: string;
}

export const NEETCODE_150: ReadonlyArray<NeetCodeSeed> = [
  // Arrays & Hashing
  {
    question_number: 1,
    title: "Contains Duplicate",
    category: "Arrays & Hashing",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/contains-duplicate",
    leetcode_url: "https://leetcode.com/problems/contains-duplicate/",
  },
  {
    question_number: 2,
    title: "Valid Anagram",
    category: "Arrays & Hashing",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/valid-anagram",
    leetcode_url: "https://leetcode.com/problems/valid-anagram/",
  },
  {
    question_number: 3,
    title: "Two Sum",
    category: "Arrays & Hashing",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/two-sum",
    leetcode_url: "https://leetcode.com/problems/two-sum/",
  },
  {
    question_number: 4,
    title: "Group Anagrams",
    category: "Arrays & Hashing",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/group-anagrams",
    leetcode_url: "https://leetcode.com/problems/group-anagrams/",
  },
  {
    question_number: 5,
    title: "Top K Frequent Elements",
    category: "Arrays & Hashing",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/top-k-frequent-elements",
    leetcode_url: "https://leetcode.com/problems/top-k-frequent-elements/",
  },
  {
    question_number: 6,
    title: "Encode and Decode Strings",
    category: "Arrays & Hashing",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/encode-and-decode-strings",
    leetcode_url: "https://leetcode.com/problems/encode-and-decode-strings/",
  },
  {
    question_number: 7,
    title: "Product of Array Except Self",
    category: "Arrays & Hashing",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/product-of-array-except-self",
    leetcode_url: "https://leetcode.com/problems/product-of-array-except-self/",
  },
  {
    question_number: 8,
    title: "Valid Sudoku",
    category: "Arrays & Hashing",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/valid-sudoku",
    leetcode_url: "https://leetcode.com/problems/valid-sudoku/",
  },
  {
    question_number: 9,
    title: "Longest Consecutive Sequence",
    category: "Arrays & Hashing",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/longest-consecutive-sequence",
    leetcode_url: "https://leetcode.com/problems/longest-consecutive-sequence/",
  },

  // Two Pointers
  {
    question_number: 10,
    title: "Valid Palindrome",
    category: "Two Pointers",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/valid-palindrome",
    leetcode_url: "https://leetcode.com/problems/valid-palindrome/",
  },
  {
    question_number: 11,
    title: "Two Sum II - Input Array Is Sorted",
    category: "Two Pointers",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/two-integer-sum-ii",
    leetcode_url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
  },
  {
    question_number: 12,
    title: "3Sum",
    category: "Two Pointers",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/3sum",
    leetcode_url: "https://leetcode.com/problems/3sum/",
  },
  {
    question_number: 13,
    title: "Container With Most Water",
    category: "Two Pointers",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/container-with-most-water",
    leetcode_url: "https://leetcode.com/problems/container-with-most-water/",
  },
  {
    question_number: 14,
    title: "Trapping Rain Water",
    category: "Two Pointers",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/trapping-rain-water",
    leetcode_url: "https://leetcode.com/problems/trapping-rain-water/",
  },

  // Sliding Window
  {
    question_number: 15,
    title: "Best Time to Buy and Sell Stock",
    category: "Sliding Window",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/buy-and-sell-crypto",
    leetcode_url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    question_number: 16,
    title: "Longest Substring Without Repeating Characters",
    category: "Sliding Window",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/longest-substring-without-duplicates",
    leetcode_url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  },
  {
    question_number: 17,
    title: "Longest Repeating Character Replacement",
    category: "Sliding Window",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/longest-repeating-substring-with-replacement",
    leetcode_url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
  },
  {
    question_number: 18,
    title: "Permutation in String",
    category: "Sliding Window",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/permutation-string",
    leetcode_url: "https://leetcode.com/problems/permutation-in-string/",
  },
  {
    question_number: 19,
    title: "Minimum Window Substring",
    category: "Sliding Window",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/minimum-window-with-characters",
    leetcode_url: "https://leetcode.com/problems/minimum-window-substring/",
  },
  {
    question_number: 20,
    title: "Sliding Window Maximum",
    category: "Sliding Window",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/sliding-window-maximum",
    leetcode_url: "https://leetcode.com/problems/sliding-window-maximum/",
  },

  // Stack
  {
    question_number: 21,
    title: "Valid Parentheses",
    category: "Stack",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/validate-parentheses",
    leetcode_url: "https://leetcode.com/problems/valid-parentheses/",
  },
  {
    question_number: 22,
    title: "Min Stack",
    category: "Stack",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/minimum-stack",
    leetcode_url: "https://leetcode.com/problems/min-stack/",
  },
  {
    question_number: 23,
    title: "Evaluate Reverse Polish Notation",
    category: "Stack",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/evaluate-reverse-polish-notation",
    leetcode_url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
  },
  {
    question_number: 24,
    title: "Generate Parentheses",
    category: "Stack",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/generate-parentheses",
    leetcode_url: "https://leetcode.com/problems/generate-parentheses/",
  },
  {
    question_number: 25,
    title: "Daily Temperatures",
    category: "Stack",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/daily-temperatures",
    leetcode_url: "https://leetcode.com/problems/daily-temperatures/",
  },
  {
    question_number: 26,
    title: "Car Fleet",
    category: "Stack",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/car-fleet",
    leetcode_url: "https://leetcode.com/problems/car-fleet/",
  },
  {
    question_number: 27,
    title: "Largest Rectangle in Histogram",
    category: "Stack",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/largest-rectangle-in-histogram",
    leetcode_url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
  },

  // Binary Search
  {
    question_number: 28,
    title: "Binary Search",
    category: "Binary Search",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/binary-search",
    leetcode_url: "https://leetcode.com/problems/binary-search/",
  },
  {
    question_number: 29,
    title: "Search a 2D Matrix",
    category: "Binary Search",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/search-2d-matrix",
    leetcode_url: "https://leetcode.com/problems/search-a-2d-matrix/",
  },
  {
    question_number: 30,
    title: "Koko Eating Bananas",
    category: "Binary Search",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/eating-bananas",
    leetcode_url: "https://leetcode.com/problems/koko-eating-bananas/",
  },
  {
    question_number: 31,
    title: "Find Minimum in Rotated Sorted Array",
    category: "Binary Search",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/find-minimum-in-rotated-sorted-array",
    leetcode_url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
  },
  {
    question_number: 32,
    title: "Search in Rotated Sorted Array",
    category: "Binary Search",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/find-target-in-rotated-sorted-array",
    leetcode_url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
  },
  {
    question_number: 33,
    title: "Time Based Key-Value Store",
    category: "Binary Search",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/time-based-key-value-store",
    leetcode_url: "https://leetcode.com/problems/time-based-key-value-store/",
  },
  {
    question_number: 34,
    title: "Median of Two Sorted Arrays",
    category: "Binary Search",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/median-of-two-sorted-arrays",
    leetcode_url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
  },

  // Linked List
  {
    question_number: 35,
    title: "Reverse Linked List",
    category: "Linked List",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/reverse-a-linked-list",
    leetcode_url: "https://leetcode.com/problems/reverse-linked-list/",
  },
  {
    question_number: 36,
    title: "Merge Two Sorted Lists",
    category: "Linked List",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/merge-two-sorted-linked-lists",
    leetcode_url: "https://leetcode.com/problems/merge-two-sorted-lists/",
  },
  {
    question_number: 37,
    title: "Reorder List",
    category: "Linked List",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/reorder-linked-list",
    leetcode_url: "https://leetcode.com/problems/reorder-list/",
  },
  {
    question_number: 38,
    title: "Remove Nth Node From End of List",
    category: "Linked List",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/remove-node-from-end-of-linked-list",
    leetcode_url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
  },
  {
    question_number: 39,
    title: "Copy List with Random Pointer",
    category: "Linked List",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/copy-linked-list-with-random-pointer",
    leetcode_url: "https://leetcode.com/problems/copy-list-with-random-pointer/",
  },
  {
    question_number: 40,
    title: "Add Two Numbers",
    category: "Linked List",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/add-two-numbers",
    leetcode_url: "https://leetcode.com/problems/add-two-numbers/",
  },
  {
    question_number: 41,
    title: "Linked List Cycle",
    category: "Linked List",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/linked-list-cycle-detection",
    leetcode_url: "https://leetcode.com/problems/linked-list-cycle/",
  },
  {
    question_number: 42,
    title: "Find the Duplicate Number",
    category: "Linked List",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/find-duplicate-integer",
    leetcode_url: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    question_number: 43,
    title: "LRU Cache",
    category: "Linked List",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/lru-cache",
    leetcode_url: "https://leetcode.com/problems/lru-cache/",
  },
  {
    question_number: 44,
    title: "Merge k Sorted Lists",
    category: "Linked List",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/merge-k-sorted-linked-lists",
    leetcode_url: "https://leetcode.com/problems/merge-k-sorted-lists/",
  },
  {
    question_number: 45,
    title: "Reverse Nodes in k-Group",
    category: "Linked List",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/reverse-nodes-in-k-group",
    leetcode_url: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
  },

  // Trees
  {
    question_number: 46,
    title: "Invert Binary Tree",
    category: "Trees",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/invert-a-binary-tree",
    leetcode_url: "https://leetcode.com/problems/invert-binary-tree/",
  },
  {
    question_number: 47,
    title: "Maximum Depth of Binary Tree",
    category: "Trees",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/depth-of-binary-tree",
    leetcode_url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
  },
  {
    question_number: 48,
    title: "Diameter of Binary Tree",
    category: "Trees",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/binary-tree-diameter",
    leetcode_url: "https://leetcode.com/problems/diameter-of-binary-tree/",
  },
  {
    question_number: 49,
    title: "Balanced Binary Tree",
    category: "Trees",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/balanced-binary-tree",
    leetcode_url: "https://leetcode.com/problems/balanced-binary-tree/",
  },
  {
    question_number: 50,
    title: "Same Tree",
    category: "Trees",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/same-binary-tree",
    leetcode_url: "https://leetcode.com/problems/same-tree/",
  },
  {
    question_number: 51,
    title: "Subtree of Another Tree",
    category: "Trees",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/subtree-of-a-binary-tree",
    leetcode_url: "https://leetcode.com/problems/subtree-of-another-tree/",
  },
  {
    question_number: 52,
    title: "Lowest Common Ancestor of a Binary Search Tree",
    category: "Trees",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/lowest-common-ancestor-in-binary-search-tree",
    leetcode_url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
  },
  {
    question_number: 53,
    title: "Binary Tree Level Order Traversal",
    category: "Trees",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/level-order-traversal-of-binary-tree",
    leetcode_url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
  },
  {
    question_number: 54,
    title: "Binary Tree Right Side View",
    category: "Trees",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/binary-tree-right-side-view",
    leetcode_url: "https://leetcode.com/problems/binary-tree-right-side-view/",
  },
  {
    question_number: 55,
    title: "Count Good Nodes in Binary Tree",
    category: "Trees",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/count-good-nodes-in-binary-tree",
    leetcode_url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
  },
  {
    question_number: 56,
    title: "Validate Binary Search Tree",
    category: "Trees",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/valid-binary-search-tree",
    leetcode_url: "https://leetcode.com/problems/validate-binary-search-tree/",
  },
  {
    question_number: 57,
    title: "Kth Smallest Element in a BST",
    category: "Trees",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/kth-smallest-integer-in-bst",
    leetcode_url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
  },
  {
    question_number: 58,
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    category: "Trees",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/binary-tree-from-preorder-and-inorder-traversal",
    leetcode_url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
  },
  {
    question_number: 59,
    title: "Binary Tree Maximum Path Sum",
    category: "Trees",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/binary-tree-maximum-path-sum",
    leetcode_url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
  },
  {
    question_number: 60,
    title: "Serialize and Deserialize Binary Tree",
    category: "Trees",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/serialize-and-deserialize-binary-tree",
    leetcode_url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
  },

  // Heap / Priority Queue
  {
    question_number: 61,
    title: "Kth Largest Element in a Stream",
    category: "Heap / Priority Queue",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/kth-largest-integer-in-a-stream",
    leetcode_url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
  },
  {
    question_number: 62,
    title: "Last Stone Weight",
    category: "Heap / Priority Queue",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/last-stone-weight",
    leetcode_url: "https://leetcode.com/problems/last-stone-weight/",
  },
  {
    question_number: 63,
    title: "K Closest Points to Origin",
    category: "Heap / Priority Queue",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/k-closest-points-to-origin",
    leetcode_url: "https://leetcode.com/problems/k-closest-points-to-origin/",
  },
  {
    question_number: 64,
    title: "Kth Largest Element in an Array",
    category: "Heap / Priority Queue",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/kth-largest-element-in-an-array",
    leetcode_url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
  },
  {
    question_number: 65,
    title: "Task Scheduler",
    category: "Heap / Priority Queue",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/task-scheduling",
    leetcode_url: "https://leetcode.com/problems/task-scheduler/",
  },
  {
    question_number: 66,
    title: "Design Twitter",
    category: "Heap / Priority Queue",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/design-twitter-feed",
    leetcode_url: "https://leetcode.com/problems/design-twitter/",
  },
  {
    question_number: 67,
    title: "Find Median from Data Stream",
    category: "Heap / Priority Queue",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/find-median-in-a-data-stream",
    leetcode_url: "https://leetcode.com/problems/find-median-from-data-stream/",
  },

  // Backtracking
  {
    question_number: 68,
    title: "Subsets",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/subsets",
    leetcode_url: "https://leetcode.com/problems/subsets/",
  },
  {
    question_number: 69,
    title: "Combination Sum",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/combination-target-sum",
    leetcode_url: "https://leetcode.com/problems/combination-sum/",
  },
  {
    question_number: 70,
    title: "Permutations",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/permutations",
    leetcode_url: "https://leetcode.com/problems/permutations/",
  },
  {
    question_number: 71,
    title: "Subsets II",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/subsets-ii",
    leetcode_url: "https://leetcode.com/problems/subsets-ii/",
  },
  {
    question_number: 72,
    title: "Combination Sum II",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/combination-target-sum-ii",
    leetcode_url: "https://leetcode.com/problems/combination-sum-ii/",
  },
  {
    question_number: 73,
    title: "Word Search",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/search-for-word",
    leetcode_url: "https://leetcode.com/problems/word-search/",
  },
  {
    question_number: 74,
    title: "Palindrome Partitioning",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/palindrome-partitioning",
    leetcode_url: "https://leetcode.com/problems/palindrome-partitioning/",
  },
  {
    question_number: 75,
    title: "Letter Combinations of a Phone Number",
    category: "Backtracking",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/combinations-of-a-phone-number",
    leetcode_url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
  },
  {
    question_number: 76,
    title: "N-Queens",
    category: "Backtracking",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/n-queens",
    leetcode_url: "https://leetcode.com/problems/n-queens/",
  },

  // Tries
  {
    question_number: 77,
    title: "Implement Trie (Prefix Tree)",
    category: "Tries",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/implement-prefix-tree",
    leetcode_url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
  },
  {
    question_number: 78,
    title: "Design Add and Search Words Data Structure",
    category: "Tries",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/design-word-search-data-structure",
    leetcode_url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
  },
  {
    question_number: 79,
    title: "Word Search II",
    category: "Tries",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/search-for-word-ii",
    leetcode_url: "https://leetcode.com/problems/word-search-ii/",
  },

  // Graphs
  {
    question_number: 80,
    title: "Number of Islands",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/count-number-of-islands",
    leetcode_url: "https://leetcode.com/problems/number-of-islands/",
  },
  {
    question_number: 81,
    title: "Max Area of Island",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/max-area-of-island",
    leetcode_url: "https://leetcode.com/problems/max-area-of-island/",
  },
  {
    question_number: 82,
    title: "Clone Graph",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/clone-graph",
    leetcode_url: "https://leetcode.com/problems/clone-graph/",
  },
  {
    question_number: 83,
    title: "Walls and Gates",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/islands-and-treasure",
    leetcode_url: "https://leetcode.com/problems/walls-and-gates/",
  },
  {
    question_number: 84,
    title: "Rotting Oranges",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/rotting-fruit",
    leetcode_url: "https://leetcode.com/problems/rotting-oranges/",
  },
  {
    question_number: 85,
    title: "Pacific Atlantic Water Flow",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/pacific-atlantic-water-flow",
    leetcode_url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
  },
  {
    question_number: 86,
    title: "Surrounded Regions",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/surrounded-regions",
    leetcode_url: "https://leetcode.com/problems/surrounded-regions/",
  },
  {
    question_number: 87,
    title: "Course Schedule",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/course-schedule",
    leetcode_url: "https://leetcode.com/problems/course-schedule/",
  },
  {
    question_number: 88,
    title: "Course Schedule II",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/course-schedule-ii",
    leetcode_url: "https://leetcode.com/problems/course-schedule-ii/",
  },
  {
    question_number: 89,
    title: "Graph Valid Tree",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/valid-tree",
    leetcode_url: "https://leetcode.com/problems/graph-valid-tree/",
  },
  {
    question_number: 90,
    title: "Number of Connected Components in an Undirected Graph",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/count-connected-components",
    leetcode_url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
  },
  {
    question_number: 91,
    title: "Redundant Connection",
    category: "Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/redundant-connection",
    leetcode_url: "https://leetcode.com/problems/redundant-connection/",
  },
  {
    question_number: 92,
    title: "Word Ladder",
    category: "Graphs",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/word-ladder",
    leetcode_url: "https://leetcode.com/problems/word-ladder/",
  },

  // Advanced Graphs
  {
    question_number: 93,
    title: "Reconstruct Itinerary",
    category: "Advanced Graphs",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/reconstruct-flight-path",
    leetcode_url: "https://leetcode.com/problems/reconstruct-itinerary/",
  },
  {
    question_number: 94,
    title: "Min Cost to Connect All Points",
    category: "Advanced Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/min-cost-to-connect-points",
    leetcode_url: "https://leetcode.com/problems/min-cost-to-connect-all-points/",
  },
  {
    question_number: 95,
    title: "Network Delay Time",
    category: "Advanced Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/network-delay-time",
    leetcode_url: "https://leetcode.com/problems/network-delay-time/",
  },
  {
    question_number: 96,
    title: "Swim in Rising Water",
    category: "Advanced Graphs",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/swim-in-rising-water",
    leetcode_url: "https://leetcode.com/problems/swim-in-rising-water/",
  },
  {
    question_number: 97,
    title: "Alien Dictionary",
    category: "Advanced Graphs",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/foreign-dictionary",
    leetcode_url: "https://leetcode.com/problems/alien-dictionary/",
  },
  {
    question_number: 98,
    title: "Cheapest Flights Within K Stops",
    category: "Advanced Graphs",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/cheapest-flight-path",
    leetcode_url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
  },

  // 1-D DP
  {
    question_number: 99,
    title: "Climbing Stairs",
    category: "1-D DP",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/climbing-stairs",
    leetcode_url: "https://leetcode.com/problems/climbing-stairs/",
  },
  {
    question_number: 100,
    title: "Min Cost Climbing Stairs",
    category: "1-D DP",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/min-cost-climbing-stairs",
    leetcode_url: "https://leetcode.com/problems/min-cost-climbing-stairs/",
  },
  {
    question_number: 101,
    title: "House Robber",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/house-robber",
    leetcode_url: "https://leetcode.com/problems/house-robber/",
  },
  {
    question_number: 102,
    title: "House Robber II",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/house-robber-ii",
    leetcode_url: "https://leetcode.com/problems/house-robber-ii/",
  },
  {
    question_number: 103,
    title: "Longest Palindromic Substring",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/longest-palindromic-substring",
    leetcode_url: "https://leetcode.com/problems/longest-palindromic-substring/",
  },
  {
    question_number: 104,
    title: "Palindromic Substrings",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/palindromic-substrings",
    leetcode_url: "https://leetcode.com/problems/palindromic-substrings/",
  },
  {
    question_number: 105,
    title: "Decode Ways",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/decode-ways",
    leetcode_url: "https://leetcode.com/problems/decode-ways/",
  },
  {
    question_number: 106,
    title: "Coin Change",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/coin-change",
    leetcode_url: "https://leetcode.com/problems/coin-change/",
  },
  {
    question_number: 107,
    title: "Maximum Product Subarray",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/maximum-product-subarray",
    leetcode_url: "https://leetcode.com/problems/maximum-product-subarray/",
  },
  {
    question_number: 108,
    title: "Word Break",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/word-break",
    leetcode_url: "https://leetcode.com/problems/word-break/",
  },
  {
    question_number: 109,
    title: "Longest Increasing Subsequence",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/longest-increasing-subsequence",
    leetcode_url: "https://leetcode.com/problems/longest-increasing-subsequence/",
  },
  {
    question_number: 110,
    title: "Partition Equal Subset Sum",
    category: "1-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/partition-equal-subset-sum",
    leetcode_url: "https://leetcode.com/problems/partition-equal-subset-sum/",
  },

  // 2-D DP
  {
    question_number: 111,
    title: "Unique Paths",
    category: "2-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/count-paths",
    leetcode_url: "https://leetcode.com/problems/unique-paths/",
  },
  {
    question_number: 112,
    title: "Longest Common Subsequence",
    category: "2-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/longest-common-subsequence",
    leetcode_url: "https://leetcode.com/problems/longest-common-subsequence/",
  },
  {
    question_number: 113,
    title: "Best Time to Buy and Sell Stock with Cooldown",
    category: "2-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/buy-and-sell-crypto-with-cooldown",
    leetcode_url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
  },
  {
    question_number: 114,
    title: "Coin Change II",
    category: "2-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/coin-change-ii",
    leetcode_url: "https://leetcode.com/problems/coin-change-ii/",
  },
  {
    question_number: 115,
    title: "Target Sum",
    category: "2-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/target-sum",
    leetcode_url: "https://leetcode.com/problems/target-sum/",
  },
  {
    question_number: 116,
    title: "Interleaving String",
    category: "2-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/interleaving-strings",
    leetcode_url: "https://leetcode.com/problems/interleaving-string/",
  },
  {
    question_number: 117,
    title: "Longest Increasing Path in a Matrix",
    category: "2-D DP",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/longest-increasing-path-in-matrix",
    leetcode_url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
  },
  {
    question_number: 118,
    title: "Distinct Subsequences",
    category: "2-D DP",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/count-subsequences",
    leetcode_url: "https://leetcode.com/problems/distinct-subsequences/",
  },
  {
    question_number: 119,
    title: "Edit Distance",
    category: "2-D DP",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/edit-distance",
    leetcode_url: "https://leetcode.com/problems/edit-distance/",
  },
  {
    question_number: 120,
    title: "Burst Balloons",
    category: "2-D DP",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/burst-balloons",
    leetcode_url: "https://leetcode.com/problems/burst-balloons/",
  },
  {
    question_number: 121,
    title: "Regular Expression Matching",
    category: "2-D DP",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/regular-expression-matching",
    leetcode_url: "https://leetcode.com/problems/regular-expression-matching/",
  },

  // Greedy
  {
    question_number: 122,
    title: "Maximum Subarray",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/maximum-subarray",
    leetcode_url: "https://leetcode.com/problems/maximum-subarray/",
  },
  {
    question_number: 123,
    title: "Jump Game",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/jump-game",
    leetcode_url: "https://leetcode.com/problems/jump-game/",
  },
  {
    question_number: 124,
    title: "Jump Game II",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/jump-game-ii",
    leetcode_url: "https://leetcode.com/problems/jump-game-ii/",
  },
  {
    question_number: 125,
    title: "Gas Station",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/gas-station",
    leetcode_url: "https://leetcode.com/problems/gas-station/",
  },
  {
    question_number: 126,
    title: "Hand of Straights",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/hand-of-straights",
    leetcode_url: "https://leetcode.com/problems/hand-of-straights/",
  },
  {
    question_number: 127,
    title: "Merge Triplets to Form Target Triplet",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/merge-triplets-to-form-target",
    leetcode_url: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
  },
  {
    question_number: 128,
    title: "Partition Labels",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/partition-labels",
    leetcode_url: "https://leetcode.com/problems/partition-labels/",
  },
  {
    question_number: 129,
    title: "Valid Parenthesis String",
    category: "Greedy",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/valid-parenthesis-string",
    leetcode_url: "https://leetcode.com/problems/valid-parenthesis-string/",
  },

  // Intervals
  {
    question_number: 130,
    title: "Insert Interval",
    category: "Intervals",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/insert-new-interval",
    leetcode_url: "https://leetcode.com/problems/insert-interval/",
  },
  {
    question_number: 131,
    title: "Merge Intervals",
    category: "Intervals",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/merge-intervals",
    leetcode_url: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    question_number: 132,
    title: "Non-overlapping Intervals",
    category: "Intervals",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/non-overlapping-intervals",
    leetcode_url: "https://leetcode.com/problems/non-overlapping-intervals/",
  },
  {
    question_number: 133,
    title: "Meeting Rooms",
    category: "Intervals",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/meeting-schedule",
    leetcode_url: "https://leetcode.com/problems/meeting-rooms/",
  },
  {
    question_number: 134,
    title: "Meeting Rooms II",
    category: "Intervals",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/meeting-schedule-ii",
    leetcode_url: "https://leetcode.com/problems/meeting-rooms-ii/",
  },
  {
    question_number: 135,
    title: "Minimum Interval to Include Each Query",
    category: "Intervals",
    difficulty: "hard",
    neetcode_url: "https://neetcode.io/problems/minimum-interval-including-query",
    leetcode_url: "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
  },

  // Math & Geometry
  {
    question_number: 136,
    title: "Rotate Image",
    category: "Math & Geometry",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/rotate-matrix",
    leetcode_url: "https://leetcode.com/problems/rotate-image/",
  },
  {
    question_number: 137,
    title: "Spiral Matrix",
    category: "Math & Geometry",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/spiral-matrix",
    leetcode_url: "https://leetcode.com/problems/spiral-matrix/",
  },
  {
    question_number: 138,
    title: "Set Matrix Zeroes",
    category: "Math & Geometry",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/set-zeroes-in-matrix",
    leetcode_url: "https://leetcode.com/problems/set-matrix-zeroes/",
  },
  {
    question_number: 139,
    title: "Happy Number",
    category: "Math & Geometry",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/non-cyclical-number",
    leetcode_url: "https://leetcode.com/problems/happy-number/",
  },
  {
    question_number: 140,
    title: "Plus One",
    category: "Math & Geometry",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/plus-one",
    leetcode_url: "https://leetcode.com/problems/plus-one/",
  },
  {
    question_number: 141,
    title: "Pow(x, n)",
    category: "Math & Geometry",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/pow-x-n",
    leetcode_url: "https://leetcode.com/problems/powx-n/",
  },
  {
    question_number: 142,
    title: "Multiply Strings",
    category: "Math & Geometry",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/multiply-strings",
    leetcode_url: "https://leetcode.com/problems/multiply-strings/",
  },
  {
    question_number: 143,
    title: "Detect Squares",
    category: "Math & Geometry",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/count-squares",
    leetcode_url: "https://leetcode.com/problems/detect-squares/",
  },

  // Bit Manipulation
  {
    question_number: 144,
    title: "Single Number",
    category: "Bit Manipulation",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/single-number",
    leetcode_url: "https://leetcode.com/problems/single-number/",
  },
  {
    question_number: 145,
    title: "Number of 1 Bits",
    category: "Bit Manipulation",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/number-of-one-bits",
    leetcode_url: "https://leetcode.com/problems/number-of-1-bits/",
  },
  {
    question_number: 146,
    title: "Counting Bits",
    category: "Bit Manipulation",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/counting-bits",
    leetcode_url: "https://leetcode.com/problems/counting-bits/",
  },
  {
    question_number: 147,
    title: "Reverse Bits",
    category: "Bit Manipulation",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/reverse-bits",
    leetcode_url: "https://leetcode.com/problems/reverse-bits/",
  },
  {
    question_number: 148,
    title: "Missing Number",
    category: "Bit Manipulation",
    difficulty: "easy",
    neetcode_url: "https://neetcode.io/problems/missing-number",
    leetcode_url: "https://leetcode.com/problems/missing-number/",
  },
  {
    question_number: 149,
    title: "Sum of Two Integers",
    category: "Bit Manipulation",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/sum-of-two-integers",
    leetcode_url: "https://leetcode.com/problems/sum-of-two-integers/",
  },
  {
    question_number: 150,
    title: "Reverse Integer",
    category: "Bit Manipulation",
    difficulty: "medium",
    neetcode_url: "https://neetcode.io/problems/reverse-integer",
    leetcode_url: "https://leetcode.com/problems/reverse-integer/",
  },
];
